---
title: "P8160 Group Project 1"
author: "
date: ""
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(glmnet)
library(MASS)
```

# Sample code
```{r}
# A sample codes for generating a data with a combinaton of true predictors and null predictors
n <- 1000
p <- 50
X <- matrix(rnorm(n * p), n, p)
b.true <- rnorm(p) * (runif(p) < 0.2)
cat("True non-zero effects:", which(b.true != 0), "\n") 
Y <- 1 + X %*% b.true + rnorm(n)
df <- data.frame(cbind(X, Y))
names(df)[p + 1] <- "y"

# Forward Selection
fit.forward <- step(object = lm(y ~ 1, data = df), 
                    scope = formula(lm(y ~ ., data = df)), 
                    direction = "forward", k = 2, trace = 0)
summary(fit.forward)

# LASSO
fit.lasso <- cv.glmnet(X, Y, nfolds = 10, type.measure = "mse")
param.best <- fit.lasso$glmnet.fit$beta[, fit.lasso$lambda == fit.lasso$lambda.1se]
param.best[param.best != 0]

```

Metric used to compare methods: MSE

```{r}
set.seed(123)
# generate data 
## set parameters
n <- 1000
p <- 20
c <- 10

# simulate index set the three types of signals
## strong signals
b_cands <- rnorm(p)
b_strong_bool <- abs(b_cands) > c * sqrt(log(p)/n)
b_strong_ind <- seq(1, p)[b_strong_bool]
## weak and correlated signals
weak_correlated_ind <- sample(seq(1,p)[-b_strong_ind], 
                                ceiling(length(seq(1,p)[-b_strong_ind])/5))
## weak and uncorrelated signals
weak_uncorrelated_ind <- seq(1,p)[-c(b_strong_ind, weak_correlated_ind)]


## generate covariance matrix
A <- matrix(runif(p^2)*2-1, ncol=p) 
A[b_strong_ind, weak_uncorrelated_ind] <- 0
Sigma <- t(A) %*% A

# generate the design matrix X
X <- mvrnorm(n = n, mu = runif(p), Sigma = Sigma)

# generate the response vector Y
Y <- X %*% b_cands

# combine X and Y to get a dataframe
df <- data.frame(cbind(X, Y))
names(df)[p + 1] <- "y"

```


```{r}
# forward selection
fit_forward <- step(object = lm(y ~ 1, data = df), 
                    scope = formula(lm(y ~ ., data = df)), 
                    direction = "forward", k = 2, trace = 0)
summary(fit_forward)

```

```{r}
# LASSO
fit.lasso <- cv.glmnet(X, Y, nfolds = 10, type.measure = "mse")
param.best <- fit.lasso$glmnet.fit$beta[, fit.lasso$lambda == fit.lasso$lambda.1se]
param.best[param.best != 0]
```

